/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as DeploymentRouteImport } from './routes/deployment'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WallpapersRouteImport } from './routes/wallpapers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentRoute = DeploymentRouteImport.update({
  id: '/deployment',
  path: '/deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WallpapersRoute = WallpapersRouteImport.update({
  id: '/wallpapers',
  path: '/wallpapers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/deployment': typeof DeploymentRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/deployment': typeof DeploymentRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRoute
  '/deployment': typeof DeploymentRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/users': typeof UsersRoute
  '/wallpapers': typeof WallpapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/deployment'
    | '/history'
    | '/login'
    | '/settings'
    | '/timeline'
    | '/users'
    | '/wallpapers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/deployment'
    | '/history'
    | '/login'
    | '/settings'
    | '/timeline'
    | '/users'
    | '/wallpapers'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/deployment'
    | '/history'
    | '/login'
    | '/settings'
    | '/timeline'
    | '/users'
    | '/wallpapers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRoute
  DeploymentRoute: typeof DeploymentRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  UsersRoute: typeof UsersRoute
  WallpapersRoute: typeof WallpapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployment': {
      id: '/deployment'
      path: '/deployment'
      fullPath: '/deployment'
      preLoaderRoute: typeof DeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallpapers': {
      id: '/wallpapers'
      path: '/wallpapers'
      fullPath: '/wallpapers'
      preLoaderRoute: typeof WallpapersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRoute,
  DeploymentRoute: DeploymentRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  UsersRoute: UsersRoute,
  WallpapersRoute: WallpapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
